# Generated by Django 4.1.7 on 2023-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todomodel",
            old_name="task",
            new_name="info",
        ),
    ]
