# Generated by Django 4.1.7 on 2023-03-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_rename_task_todomodel_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="info",
            field=models.CharField(max_length=100),
        ),
    ]
